version: 0.0
Resources:
  - MyLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: restaurantApiFunction   
        Alias: prod                  
        CurrentVersion: $LATEST     
        TargetVersion: 1             
