version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "my-react-app-lambda"
        Alias: "live"
        CurrentVersion: "<existing_version>"  # Replace with the current alias version
        TargetVersion: "<new_version>"       # Replace with the desired target version
