version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "my-react-app-lambda"
        Alias: "live"
        CurrentVersion: "$LATEST"  # Set to current version
        TargetVersion: "1"         # Set to a specific version to deploy
