version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Zipping the Lambda function and AppSpec file"
      - zip -r function.zip lambda_handler.py appspec.yaml

artifacts:
  files:
    - function.zip
  discard-paths: yes
  encryption: aws:kms
